[config]
default_to_workspace = false

[tasks.ignore-members]
workspace = false

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.install-bare-metal]
command = "rustup"
args = ["target", "add", "thumbv7em-none-eabi"]

[tasks.build-bare-metal]
dependencies = ["install-bare-metal"]
command = "cargo"
args = ["build", "--no-default-features", "--target", "thumbv7em-none-eabi"]

[tasks.build]
command = "cargo"
args = ["build"]

[tasks.test]
command = "cargo"
args = ["test"]

[tasks.build_convert]
command = "cargo"
args = ["build", "--bin", "convert_old", "--release", "--features", "convert"]

[tasks.format_inst]
[tasks.format-inst]
install_crate = { crate_name = "rustfmt", rustup_component_name = "rustfmt", binary = "rustfmt", test_arg = "--help" }

[tasks.format]
dependencies = ["format-inst"]
command = "cargo"
args = ["fmt"]

[tasks.format-check]
dependencies = ["format-inst"]
command = "cargo"
args = ["fmt", "--check"]

[tasks.clippy-inst]
install_crate = { crate_name = "clippy", rustup_component_name = "clippy", binary = "clippy", test_arg = "--help" }

[tasks.clippy]
dependencies = ["clippy-inst"]
command = "cargo"
args = ["clippy", "--", "--deny", "warnings"]

[tasks.compile-header-fix]
command = "cargo"
args = ["build", "--manifest-path", "header-fix/Cargo.toml", "--release"]

[tasks.header-add]
dependencies = ["compile-header-fix"]
command = "./header-fix/target/release/header-fix"
args = ["--glob", "**/*.rs", "HEADER-APACHE2"]

[tasks.header-check]
dependencies = ["compile-header-fix"]
command = "./header-fix/target/release/header-fix"
args = ["--check", "--glob", "**/*.rs", "HEADER-APACHE2"]

[tasks.audit-inst]
command = "cargo"
args = ["install", "cargo-audit"]

[tasks.audit]
dependencies = ["audit-inst"]
command = "cargo"
args = ["audit"]

[tasks.cov]
command = "cargo"
args = ["llvm-cov", "--workspace", "--lcov", "--output-path", "lcov.info"]

[tasks.udeps-inst]
toolchain = "nightly"
command = "cargo"
args = ["install", "cargo-udeps", "--locked"]

[tasks.udeps]
dependencies = ["udeps-inst"]
toolchain = "nightly"
command = "cargo"
args = ["udeps", "--all-targets"]

[tasks.check-risc0-deps]
description = "Check that all risc0 dependencies are up to date up to their respective minor versions"
command = "cargo"
args = ["test", "--test", "check_risc0_deps"]

[tasks.ci-common]
dependencies = ["check-risc0-deps", "build", "build-bare-metal", "test", "build_convert", "clippy", "audit", "udeps"]

[tasks.ci]
dependencies = ["format", "header-add", "ci-common"]

[tasks.ci-remote]
dependencies = ["format-check", "header-check", "ci-common"]
